image: docker:18.09.8-dind # A Docker 19 based image does not work on Gitlab shared runners (November 2019)
services:
  - docker:18.09.8-dind
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  LOCAL_ES_NAME: $CI_REGISTRY_IMAGE/elasticsearch:$CI_COMMIT_SHORT_SHA

stages:
  - build
  - pretest
  - test
  - push
  - deploy

.all-stable-branches:
  only:
    refs:
      - development
    changes:
      - "**/*"

## Wallet Frontend
wallet-frontend-test-suite:
  stage: test
  image: node:12
  before_script:
    - cd applications/wallet/frontend
    - npm ci
  script:
    - npm run lint
    - npm run test:cover
    - npm run size
  only:
    refs:
      - merge_requests
    changes:
      - applications/wallet/frontend/**/*
      - .gitlab-ci.yml

wallet-frontend-test-suite-all-stable-branches:
  extends:
    - wallet-frontend-test-suite
    - .all-stable-branches

## Wallet Backend
wallet-backend-test-suite:
  stage: test
  image: mc706/pipenv-3.7
  services:
    - name: postgres:9.6.9
      alias: postgres
  variables:
    POSTGRES_PASSWORD: a8fnnbe934j
    POSTGRES_USER: wallet
    POSTGRES_DB: wallet
    PG_HOST: postgres
  script:
    - cd applications/wallet
    - pipenv sync
    - cd app
    - pipenv run flake8
    - pipenv run pytest --cov=.
  only:
    refs:
      - merge_requests
    changes:
      - applications/wallet/app/**/*
      - .gitlab-ci.yml

wallet-backend-test-suite-all-stable-branches:
  extends:
    - wallet-backend-test-suite
    - .all-stable-branches

## Wallet Container Build Validation
wallet-container-build-validation:
  only:
    - development
  stage: test
  image: docker:18.09.8-dind
  services:
    - docker:18.09.8-dind
  script:
    - docker build --pull --no-cache --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA --file applications/wallet/Dockerfile .

## Backend Python Lint
backend-py-lint:
  image: python:3.7.5
  stage: pretest
  allow_failure: false
  script:
    - python -m pip install flake8
    - flake8 --config .flake8.cfg sdk client/python containers/zmlp-py3-base services/analyst
    - flake8 --config .flake8.cfg containers/zmlp-plugins-base containers/zmlp-plugins-core containers/zmlp-plugins-analysis
  only:
    refs:
      - merge_requests
    changes:
      - client/python/**/*.py
      - sdk/**/.py
      - containers/**/*.py
      - services/analyst/**/*.py
      - .gitlab-ci.yml

backend-py-lint-all-stable-branches:
  extends:
    - backend-py-lint
    - .all-stable-branches

## Backend Kotlin Lint
backend-kotlin-lint:
  image: kkopper/ktlint
  stage: pretest
  script:
    - ktlint services/**/*.kt lib/**/*.kt
  only:
    refs:
      - merge_requests
    changes:
      - services/**/*.kt
      - lib/**/*.kt
      - .gitlab-ci.yml

backend-kotlin-lint-all-stable-branches:
  extends:
    - backend-kotlin-lint
    - .all-stable-branches

# SDK Test
# Testing other containers requires building containers
# Testing analyst requires it can pull plugin containers.
sdk-unit-tests:
  image: python:3.7.5
  stage: test
  allow_failure: true
  script:
    - python -m pip install pipenv pytest
    - cd client/python
    - python setup.py install
    - pytest
    - cd ../../sdk
    - python setup.py install
    - pytest
    - cd ../containers/zmlp-plugins-base
    - pip install -r requirements.txt
    - pytest
  only:
    refs:
      - merge_requests
    changes:
      - client/python/**/*
      - sdk/**/*
      - containers/zmlp-plugins-base/**/*
      - .gitlab-ci.yml

plugin-container-tests:
  image: zmlp/docker-buildx
  stage: test
  services:
    - docker:19.03-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
  retry: 2
  before_script:
    - apk add docker-compose
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"
  script:
    - ./buildx analyst zmlp-py3-base zmlp-py3-client zmlp-py3-sdk zmlp-plugins-base zmlp-plugins-models zmlp-plugins-core zmlp-plugins-analysis
    - docker run -v ${PWD}/test-data:/test-data zmlp/plugins-core:latest pytest -s /zvi/pylib
    - docker run -v ${PWD}/test-data:/test-data zmlp/plugins-analysis:latest pytest -s /zvi/pylib
  only:
    refs:
      - merge_requests
    changes:
      - client/python/**/*
      - sdk/**/*
      - containers/**/*
      - .gitlab-ci.yml


sdk-java-unit-tests:
  image: maven:3.6-jdk-11
  stage: test
  allow_failure: true
  script:
    - mvn test verify -f client/java -q
  only:
    refs:
      - merge_requests
    changes:
      - client/java/**/*
      - containers/zmlp-plugins-base/**/*
      - .gitlab-ci.yml

sdk-unit-tests-all-stable-branches:
  retry: 1
  extends:
    - sdk-unit-tests
    - sdk-java-unit-tests
    - .all-stable-branches

docker_hub_build_push:
  image: zmlp/docker-buildx
  stage: push
  services:
    - docker:19.03-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://localhost:2375
  retry: 2
  before_script:
    - apk add docker-compose
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS"
  script:
    - ./buildx
    - docker push zmlp/archivist:latest
    - docker push zmlp/officer:latest
    - docker push zmlp/wallet:latest
    - docker push zmlp/elasticsearch:latest
    - docker push zmlp/authserver:latest
    - docker push zmlp/apigateway:latest
    - docker push zmlp/py3-base:latest
    - docker push zmlp/py3-client:latest
    - docker push zmlp/py3-sdk:latest
    - docker push zmlp/plugins-base:latest
    - docker push zmlp/plugins-models:latest
    - docker push zmlp/plugins-core:latest
    - docker push zmlp/plugins-analysis:latest
    - docker push zmlp/analyst:latest
    - docker push zmlp/jvm-common:latest
    - docker push zmlp/ml-bbq:latest
  only:
    - development

deploy_development:
  image: google/cloud-sdk
  retry: 1
  variables:
    DEPLOY_SCRIPT: ./deployment/bin/k8s-redeploy.sh
    PROJECT: zmlp-258901
  stage: deploy
  only:
    - development
  before_script:
    - echo $SA_JSON > ./sa.json
    - gcloud auth activate-service-account $SA_EMAIL --key-file=./sa.json
    - gcloud container clusters get-credentials zmlp --zone us-central1-a --project ${PROJECT}
  script:
    - ${DEPLOY_SCRIPT} deployment ${PROJECT} analyst
    - ${DEPLOY_SCRIPT} deployment ${PROJECT} api-gateway
    - ${DEPLOY_SCRIPT} deployment ${PROJECT} archivist
    - ${DEPLOY_SCRIPT} deployment ${PROJECT} auth-server
    - ${DEPLOY_SCRIPT} statefulset ${PROJECT} elasticsearch-master
    - ${DEPLOY_SCRIPT} statefulset ${PROJECT} elasticsearch-data
    - ${DEPLOY_SCRIPT} deployment ${PROJECT} officer
    - ${DEPLOY_SCRIPT} deployment ${PROJECT} wallet
    - ${DEPLOY_SCRIPT} deployment ${PROJECT} ml-bbq

# Kotlin services - Unit tests - Step 1
services_build_artifacts:
  image: maven:3.6.2-jdk-11-slim
  stage: build
  script:
    - cd services/elasticsearch
    - mvn clean install -Dmaven.test.skip=true
  artifacts:
    paths:
      - services/elasticsearch/es-similarity/target/releases/es-similarity.zip
  only:
    refs:
      - merge_requests
    changes:
      - services/**/*
      - lib/**/*
      - .gitlab-ci.yml

services_build_artifacts-all-stable-branches:
  extends:
    - services_build_artifacts
    - .all-stable-branches

# Kotlin services - Unit tests - Step 2
services_push_to_local_registry:
  image: docker:18.09.8-dind
  stage: pretest
  retry: 2
  services:
    - docker:18.09.8-dind
  script:
    - cd services/elasticsearch
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $LOCAL_ES_NAME .
    - docker push $LOCAL_ES_NAME
  only:
    refs:
      - merge_requests
    changes:
      - services/**/*
      - .gitlab-ci.yml

services_push_to_local_registry-all-stable-branches:
  extends:
    - services_push_to_local_registry
    - .all-stable-branches

services_unit_tests:
  stage: test
  image: maven:3.6-jdk-11
  retry: 1
  services:
    - name: redis:alpine
      alias: redis
    - name: minio/minio
      alias: minio
      command: ["server", "/data"]
    - name: postgres:9.6.9
      alias: postgres
    - name: $LOCAL_ES_NAME
      alias: elasticsearch
      command: ["bin/elasticsearch", "-Ediscovery.type=single-node"]
    - name: rabbitmq:3.8-management-alpine
      alias: rabbitmq
  variables:
    POSTGRES_PASSWORD: "zorroa"
    POSTGRES_USER: "zorroa"
    POSTGRES_DB: "zorroa"
    PGDATA: "/var/lib/postgresql/data/pgdata"
    ARCHIVIST_ES_URL: "http://localhost:9200"
    SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5432/zorroa?currentSchema=archivist_test"
    SPRING_RABBITMQ_USERNAME: "guest"
    SPRING_RABBITMQ_PASSWORD: "guest"
    LOGGING_LEVEL_COM_ZORROA: "WARN"
    USER: "gitlab"
    ZMLP_STORAGE_PROJECT_ACCESSKEY: "qwerty123"
    ZMLP_STORAGE_PROJECT_SECRETKEY: "123qwerty"
    ZMLP_STORAGE_PROJECT_URL: "http://localhost:9000"
    ZMLP_STORAGE_PIPELINE_ACCESSKEY: "qwerty123"
    ZMLP_STORAGE_PIPELINE_SECRETKEY: "123qwerty"
    ZMLP_STORAGE_PIPELINE_URL: "http://localhost:9000"
    ZMLP_STORAGE_SYSTEM_ACCESSKEY: "qwerty123"
    ZMLP_STORAGE_SYSTEM_SECRETKEY: "123qwerty"
    ZMLP_STORAGE_SYSTEM_URL: "http://localhost:9000"
    MINIO_ACCESS_KEY: "qwerty123"
    MINIO_SECRET_KEY: "123qwerty"
    MXNET_OS: "linux"
  script:
    - export
    - IP="$(cat /etc/hosts |grep $HOSTNAME|cut -d$'\t' -f1)"
    - ARCHIVIST_ES_URL="http://${IP}:9200"
    - ZMLP_STORAGE_PIPELINE_URL="http://${IP}:9000"
    - ZMLP_STORAGE_PROJECT_URL="http://${IP}:9000"
    - ZMLP_STORAGE_SYSTEM_URL="http://${IP}:9000"
    - mvn clean install -f lib/jvm-common -q -Dmaven.test.skip=true
    - mvn test verify -f lib/jvm-common -q
    - mvn clean install -f services/auth-server -q -Dmaven.test.skip=true
    - mvn test verify -f services/archivist -q
    - SPRING_DATASOURCE_URL="jdbc:postgresql://localhost:5432/zorroa?currentSchema=auth_test"
    - mvn test verify -f services/auth-server -q
    - mvn test verify -f services/officer -q
  only:
    refs:
      - merge_requests
    changes:
      - services/**/*
      - .gitlab-cy.yml

services_unit_tests-all-stable-branches:
  extends:
    - services_unit_tests
    - .all-stable-branches
# Kotlin Services Jobs
#sdk-containers-tests:
#  stage: test
#  before_script:
#    - apk add --no-cache python3 # for build-images.py
#    - pip3 install wheel
#    - ./build-images.py
#  script:
#    - docker run -v $PWD/test-data:/test-data --entrypoint pytest zmlp-plugins-analysis /zvi/pylib/zplugins
#    - docker run -v $PWD/test-data:/test-data --entrypoint pytest zmlp-plugins-core /zvi/pylib/zplugins

