
version: '3.6'
services:

  ## Unit testing services.

  # Elastic Search instance used for local development servers.
  es:
    build:
      context: elasticsearch
      args:
        node_type: single
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      discovery.zen.minimum_master_nodes: "1"
      cluster.name: "zorroa-es-cluster"
      network.host: "0.0.0.0"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"

  prometheus:
    image: "prom/prometheus"
    depends_on:
      - "archivist"
    ports:
        - "9090:9090"
    secrets:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml

  # Grafana server connected to elasticsearch instance
  grafana:
    links:
      - "prometheus"
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_DEFAULT_THEME: dark
      # GF_PATHS_PROVISIONING: /etc/grafana/provisioning
    volumes:
      - "./localdev/monitoring/grafana/provisioning:/etc/grafana/provisioning"
      - "./localdev/monitoring/grafana/dashboards:/var/lib/grafana/dashboards"

  # Postgres instance used for local development servers.
  postgres:
    image: "postgres:9.6.9"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: zorroa
      POSTGRES_USER: zorroa
      POSTGRES_DB: zorroa
      PGDATA: /var/lib/postgresql/data/pgdata

  # Local Archivist server.
  archivist:
    links:
       - "es"
       - "postgres"
    build:
      context: archivist
    ports:
      - 8080:8080
    volumes:
      - "./localdev/shared:/shared"
      - "./localdev/monitoring:/monitoring"
      - "./localdev/zorroa-archivist-config:/config"
      - "./archivist/target:/service"
      - "../zorroa-test-data:/zorroa-test-data"

  # Local Analyst server.
  analyst:
    build: ../zorroa-plugin-sdk
    links:
       - "archivist"
    ports:
      - 5000:5000
    volumes:
      - "./localdev/shared:/shared"
      - "./localdev/zorroa:/zorroa"
      - "../zorroa-test-data:/zorroa-test-data"
  curator:
     build: ../zorroa-js-curator
     user: node
     ports:
       - 80:8081
       - 443:8443
     environment:
         NODE_ENV: "production"
         ARCHIVIST_API_URL: "http://archivist:8080"
         CURATOR_PORT_SECURE: "8443"
         SSL_CERT_PATH: "./"

secrets:
  prometheus.yml:
    file: ./localdev/monitoring/prometheus.yml
