version: "3.6"
services:
  # Postgres instance used for local development servers.
  postgres:
    image: "postgres:9.6.9"
    ports:
      - "5432:5432"
    volumes:
      - ./dev/postgres_init_scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  # MinIO object storage service.
  minio:
    image: "minio/minio:RELEASE.2020-02-07T23-28-16Z"
    ports:
      - "9000:9000"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: qwerty123
      MINIO_SECRET_KEY: 123qwerty

  # Elastic Search instance used for local development servers.
  es1:
    image: zmlp/elasticsearch:latest
    build:
      context: services/elasticsearch
      args:
        node_type: single
        MINIO_ACCESS_KEY: qwerty123
        MINIO_SECRET_KEY: 123qwerty
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      discovery.zen.minimum_master_nodes: "1"
      cluster.name: "zorroa-es-cluster"
      network.host: "0.0.0.0"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      MINIO_URL: http://minio:9000
      MINIO_DEFAULT_PROTOCOL: http

  eshq:
    image: elastichq/elasticsearch-hq
    ports:
      - "5001:5000"
    depends_on:
      - es1

  # API Gateway
  api-gateway:
    image: zmlp/apigateway:latest
    build:
      context: services/api-gateway
    depends_on:
      - auth-server
      - archivist
      - ml-bbq
    ports:
      - 8080:80
    environment:
      ARCHIVIST_HOST: archivist:8080
      AUTH_SERVER_HOST: auth-server:9090
      MLBBQ_SERVER_HOST: ml-bbq:8282

  ml-bbq:
    image: zmlp/ml-bbq:latest
    depends_on:
      - auth-server
      - zmlp-plugins-models
    ports:
      - "8282:8282"
    build:
      context: services/mlbbq
    environment:
      ZMLP_SECURITY_AUTHSERVER_URL : http://auth-server:9090

  # Auth server
  auth-server:
    image: zmlp/authserver:latest
    depends_on:
      - postgres
      - minio
      - zmlp-jvm-common
    ports:
      - "9090:9090"
    build:
      context: services/auth-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/zorroa?currentSchema=auth
      ZMLP_SECURITY_INCEPTIONKEY: ewogICAgIm5hbWUiOiAiYWRtaW4ta2V5IiwKICAgICJwcm9qZWN0SWQiOiAiMDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwIiwKICAgICJpZCI6ICI0MzM4YTgzZi1hOTIwLTQwYWItYTI1MS1hMTIzYjE3ZGYxYmEiLAogICAgImFjY2Vzc0tleSI6ICJSRGMyTmtFeVFVWXRRakJHUXkwMFFVVkVMVGsxTVRZdE9UVTBOME5DTXpOQ05rTTJDZyIsCiAgICAic2VjcmV0S2V5IjogInBjZWtqRFZfaXBTTVhBYUJxcXRxNkp3eTVGQU1uamVoVVFyTUVoYkc4VzAxZ2lWcVZMZkVOOUZkTUl2enUwcmIiLAogICAgInBlcm1pc3Npb25zIjogW10KfQoK
      ZMLP_STORAGE_SYSTEM_ACCESSKEY: qwerty123
      ZMLP_STORAGE_SYSTEM_SECRETKEY: 123qwerty
      JAVA_OPTS: "-Xms1g -Xmx1g -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=70 -XX:G1HeapRegionSize=16m"

  # Local Archivist server.
  archivist:
    image: zmlp/archivist:latest
    depends_on:
      - es1
      - postgres
      - minio
      - zmlp-jvm-common
    environment:
      SENTRY_ENVIRONMENT: localdev
      ZMLP_STORAGE_PROJECT_ACCESSKEY: qwerty123
      ZMLP_STORAGE_PROJECT_SECRETKEY: 123qwerty
      ZMLP_STORAGE_SYSTEM_URL: http://minio:9000
      ZMLP_STORAGE_SYSTEM_ACCESSKEY: qwerty123
      ZMLP_STORAGE_SYSTEM_SECRETKEY: 123qwerty
      ZMLP_STORAGE_PROJECT_URL: http://minio:9000
      ANALYST_SHAREDKEY: 8248911982254469B56C849A29CE0E0F
      ZMLP_SECURITY_AUTHSERVER_SERVICEKEY: ewogICAgImFjY2Vzc0tleSI6ICJSRGMyTmtFeVFVWXRRakJHUXkwMFFVVkVMVGsxTVRZdE9UVTBOME5DTXpOQ05rTTJDZyIsCiAgICAic2VjcmV0S2V5IjogInBjZWtqRFZfaXBTTVhBYUJxcXRxNkp3eTVGQU1uamVoVVFyTUVoYkc4VzAxZ2lWcVZMZkVOOUZkTUl2enUwcmIiCn0KCg==
      JAVA_OPTS: "-Xms1g -Xmx1g -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=70 -XX:G1HeapRegionSize=16m"
    build:
      context: services/archivist
    volumes:
      - "./dev/config/monitoring:/monitoring"
      - "./dev/config/archivist/application.properties:/service/config/application.properties"

  officer:
    image: zmlp/officer:latest
    depends_on:
      - zmlp-jvm-common
      - minio
      - redis
    build:
      context: services/officer
    ports:
      - 7078:7078
    environment:
      ZMLP_STORAGE_PROJECT_URL: http://minio:9000
      ZMLP_STORAGE_PROJECT_ACCESSKEY: qwerty123
      ZMLP_STORAGE_PROJECT_SECRETKEY: 123qwerty
      ZMLP_STORAGE_CLIENT: minio
      REDIS_HOST: redis:6379

  analyst:
    image: zmlp/analyst:latest
    depends_on:
      - archivist
      - zmlp-py3-sdk
    build:
      context: services/analyst
    ports:
      - 5000:5000
    volumes:
      - "/tmp:/tmp"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      ANALYST_DOCKER_PULL: "false"
      ANALYST_SHAREDKEY: 8248911982254469B56C849A29CE0E0F
      ZMLP_SERVER: http://archivist:8080
      OFFICER_URL: http://officer:7078

  # Console web application.
  wallet:
    image: zmlp/wallet:latest
    ports:
      - 80:80
    build:
      context: .
      dockerfile: applications/wallet/Dockerfile
      args:
        CI_COMMIT_SHA: $CI_COMMIT_SHA
    environment:
      DJANGO_SETTINGS_MODULE: wallet.settings
      DEBUG: "true"
      BROWSABLE: "true"
      PG_HOST: postgres
      ZMLP_API_URL: http://api-gateway:80
      INCEPTION_KEY_B64: ewogICAgImFjY2Vzc0tleSI6ICJSRGMyTmtFeVFVWXRRakJHUXkwMFFVVkVMVGsxTVRZdE9UVTBOME5DTXpOQ05rTTJDZyIsCiAgICAic2VjcmV0S2V5IjogInBjZWtqRFZfaXBTTVhBYUJxcXRxNkp3eTVGQU1uamVoVVFyTUVoYkc4VzAxZ2lWcVZMZkVOOUZkTUl2enUwcmIiCn0KCg==
      GOOGLE_OAUTH_CLIENT_ID: 980622341235-39kks0r3pkl0iotcb8mt6iclbvj98mml
      SUPERADMIN: "true"
      ENVIRONMENT: localdev
      ENABLE_SENTRY: "false"
      USE_MODEL_IDS_FOR_LABEL_FILTERS: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - postgres
      - api-gateway

  # These services are only here because their images need to be built.
  zmlp-jvm-common:
    image: zmlp/jvm-common:latest
    build:
      context: lib/jvm-common
    command: echo

  zmlp-py3-base:
    image: zmlp/py3-base:latest
    build:
      context: containers/zmlp-py3-base
    command: echo

  zmlp-py3-client:
    image: zmlp/py3-client:latest
    depends_on:
      - zmlp-py3-base
    build:
      context: client/python
    command: echo

  zmlp-py3-zvi:
    image: zmlp/py3-zvi:latest
    depends_on:
      - zmlp-py3-client
    build:
      context: client/zvi
    command: echo

  zmlp-py3-sdk:
    image: zmlp/py3-sdk:latest
    depends_on:
      - zmlp-py3-client
    build:
      context: sdk
    command: echo

  zmlp-plugins-base:
    image: zmlp/plugins-base:latest
    depends_on:
      - zmlp-py3-sdk
    build:
      context: containers/zmlp-plugins-base
    command: echo

  zmlp-plugins-core:
    image: zmlp/plugins-core:latest
    depends_on:
      - zmlp-plugins-base
    build:
      context: containers/zmlp-plugins-core
    command: echo

  zmlp-plugins-models:
    image: zmlp/plugins-models:latest
    depends_on:
      - zmlp-plugins-base
    build:
      context: containers/zmlp-plugins-models
    command: echo

  zmlp-plugins-train:
    image: zmlp/plugins-train:latest
    depends_on:
      - zmlp-plugins-models
    build:
      context: containers/zmlp-plugins-train
    command: echo

  zmlp-plugins-analysis:
    image: zmlp/plugins-analysis:latest
    depends_on:
      - zmlp-plugins-models
    build:
      context: containers/zmlp-plugins-analysis
    command: echo

  reporter:
    image: zmlp/reporter:latest
    depends_on:
      - zmlp-plugins-base
    build:
      context: .
      dockerfile: services/reporter/Dockerfile
    command: echo
