version: "3.6"
services:
  sandbox:
    image: zmlp/sandbox
    ports:
      - 8501:8501
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOONAI_API_URL: http://api-gateway:80
    volumes:
      - "./applications/sandbox/sandbox:/sandbox"
